name: test
on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir mydir && touch mydir/hello.txt && cd mydir && ls
      - run: ls
