name: Build Docker
on:
    workflow_dispatch:
      inputs:
        latest-tag:
            description: "Publish Release"
            required: false
            default: false
        daily-tag:
            description: "Publish Daily"
            required: false
            default: true

permissions:
    packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-docker@master
        with:
          source: quarto-1.3.306-linux-amd64.deb
          version: "v1.3.306"
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          org: ${{ github.repository_owner }}
          name: quarto-test
          latest: ${{ inputs.latest-tag }}
          daily: ${{ inputs.daily-tag }}
 
